In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

df

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,B,C,B,D,C,C,D,B,A,D
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,C,A,C,A,C,A,B,A,B,A
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,NaN,A,B,A,NaN,C,NaN,NaN,NaN,NaN
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,D,NaN,B,A,D,C,A,E,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,NaN,E,C,NaN,B,C,A,NaN,NaN,A
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Things I need to do with this data:
#   1. Determine whether or not there is a relationship between the students' score on the test and the students'
#     final course grade. (Compare final score to pre-test score for this? Or both pre-test and post-test?)
#   2. Determine whether or not there is an increase in performance between pre and post tests, both for individual
#     students and the class as a whole. (Maybe start with whole and then figure out indiviudal?)
#   3. Determine whether or not there is difference in grade between instructors and a difference in grade between
#     terms.

# Write statistical analysis about results at the end. (Maybe write analysis between code? Figure out later.)

# How to accomplish these things:
#   ~ Graphs maybe?
#   ~ Averages?

# Link to assignment page: https://github.com/sgb7/2020-spring-cs232/tree/master/assignments/3%20-%20data%20analysis

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Participant Code  148 non-null    object
 1   Term              147 non-null    float64
 2   Test              147 non-null    object
 3   Instructor        147 non-null    object
 4   LetterGrade       147 non-null    object
 5   PercentGrade      147 non-null    float64
 6   Q1                115 non-null    object
 7   Q2                98 non-null     object
 8   Q3                112 non-null    object
 9   Q4                91 non-null     object
 10  Q5                123 non-null    object
 11  Q6                108 non-null    object
 12  Q7                80 non-null     object
 13  Q8                113 non-null    object
 14  Q9                87 non-null     object
 15  Q10               100 non-null    object
 16  Q11               98 non-null     object
 17  Q12               90 non-null     object
 18  Q13               83 non-null     object
 19  Q14               83 non-null     object
 20  Q15               72 non-null     object
 21  Q16               86 non-null     object
 22  Q17               74 non-null     object
 23  Q18               74 non-null     object
 24  Q19               78 non-null     object
 25  Q20               84 non-null     object
 26  Q21               79 non-null     object
 27  Q22               70 non-null     object
 28  Q23               85 non-null     object
 29  Q24               64 non-null     object
 30  Q25               79 non-null     object
 31  Q26               67 non-null     object
 32  Q27               74 non-null     object
dtypes: float64(2), object(31)
memory usage: 38.5+ KB

In [6]:
df.shape

(149, 33)

In [7]:
df = df.drop_duplicates()

df.shape

(149, 33)

In [8]:
# Wait, are the letter and percent grades I'm given the grades for the test or the grades for the whole course? Am
# I ever actually given both the course grade and the test grade plainly? I think the grades I'm given are the
# course grades, but I'll have to double check. So does that mean I have to calculate the test grade with the 
# answers and key I'm given?

# Okay yeah, I'm pretty sure now that the grade/percentage I'm given is the course grade. If I want to compare it
# to the test grade I need to process the answers somehow.

# Also, should I take both the letter grade and the percentage grade into account, since letter grades can be given
# more flexiably by teachers? Just the letter grade could probably be easier. We'll see how it goes.

In [9]:
# How to go about discarding incomplete data? Is there away to select specific cells, rather than whole rows or
# columns? Research. Either way, I think that's where I want to start with each analysis.

# Okay, so I think I need to go through and compare each student's test answers to the key, see how many answers
# match with the key, put that number over 27 and calculate percentage--side note: let's do the course grade by
# percentage too so I don't have to worry about inaccurate conversions--and put that number in the same row, at the
# end, in a new column called 'Test Grade.'

# Things to look up for this:
#     ~ Comparing rows. (Multiple rows to a singular row, really, but worse comes to worse, I can probably use a
#       a for loop of some kind.)
#     ~ Creating new columns.

In [10]:
df

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,B,C,B,D,C,C,D,B,A,D
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,C,A,C,A,C,A,B,A,B,A
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,NaN,A,B,A,NaN,C,NaN,NaN,NaN,NaN
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,D,NaN,B,A,D,C,A,E,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,NaN,E,C,NaN,B,C,A,NaN,NaN,A
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df['TestScore'] = 0

df

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,A,C,A,C,A,B,A,B,A,0
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,A,B,A,NaN,C,NaN,NaN,NaN,NaN,0
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,NaN,B,A,D,C,A,E,B,B,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,0
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,E,C,NaN,B,C,A,NaN,NaN,A,0
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [12]:
def find_test_score(row):
    key = df.loc[0, "Q1":"Q27"]
    points = 0
    count = 0
    #TODO: Compare test answers with key and get test score
    for numCols in key:
        count = count + 1
        currentCol = 'Q' + str(count)
        value1 = key[currentCol]
        value2 = row[currentCol]
        if value1 == value2:
            points = points + 1   
    return (points/27)*100

count = 0
rowNum = 2
while count < 147:
    count = count + 1
    tempRow = df.loc[rowNum, "Q1":"Q27"]
    score = find_test_score(tempRow)
    df.loc[rowNum, 'TestScore'] = score
    rowNum = rowNum + 1
    
    
df['TestScore'].astype(int)
df.round(2)

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.00
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,A,C,A,C,A,B,A,B,A,14.81
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,A,B,A,NaN,C,NaN,NaN,NaN,NaN,25.93
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,NaN,B,A,D,C,A,E,B,B,25.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,18.52
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,E,C,NaN,B,C,A,NaN,NaN,A,7.41
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.41
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00

In [53]:
def sort_grades(column):
    A = 0
    B = 0
    C = 0
    D = 0
    F = 0
    for value in column:
        if value >= 90 and value <= 100:
            A = A + 1
        elif value >= 80 and value <= 89.9:
            B = B + 1
        elif value >= 70 and value <= 79.9:
            C = C + 1
        elif value >= 60 and value <= 69.9:
            D = D + 1
        else:
            F = F + 1
    print("   Number of students with a 90-100 grade: " + str(A))
    print("   Number of students with a 80-89 grade: " + str(B))
    print("   Number of students with a 70-79 grade: " + str(C))
    print("   Number of students with a 60-69 grade: " + str(D))
    print("   Number of students with a grade of 59 or lower: " + str(F))

In [54]:
# TEST SCORE VS FINAL COURSE GRADE:

In [57]:
AvgTestScore = df.loc[2 : 148, 'TestScore'].mean().round(2)
TestScoresOverall = df.loc[2 : 148, 'TestScore']

AvgPercentGrade = df['PercentGrade'].mean().round(2)
FinalGradesOverall = df.loc[2 : 148, 'PercentGrade']

print("Average Test Score: " + str(AvgTestScore))
print("Test Scores Overall: ")
sort_grades(TestScoresOverall)

print("\n")

print("Average Final Course Grade: " + str(AvgPercentGrade))
print("Final Course Grades Overall: ")
sort_grades(FinalGradesOverall)

Average Test Score: 16.98
Test Scores Overall:
   Number of students with a 90-100 grade: 0
   Number of students with a 80-89 grade: 0
   Number of students with a 70-79 grade: 1
   Number of students with a 60-69 grade: 0
   Number of students with a grade of 59 or lower: 146


Average Final Course Grade: 80.81
Final Course Grades Overall:
   Number of students with a 90-100 grade: 60
   Number of students with a 80-89 grade: 22
   Number of students with a 70-79 grade: 27
   Number of students with a 60-69 grade: 7
   Number of students with a grade of 59 or lower: 31

In [58]:
# Conclusion:

# A student's test score and final course grade are unrelated. All except one of the test scores are in the F range,
# while final course grades are more evenly spread out across the board. Therefore, a poor test grade does not mean
# a student will get a poor final course grade.

In [ ]:
# PRE-TEST VS POST-TEST

In [16]:
PreTestOnly = df[df.Test != 'Post']
PreTestOnly

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,A,B,A,NaN,C,NaN,NaN,NaN,NaN,25.925926
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,NaN,B,A,D,C,A,E,B,B,25.925926
6,22,1.0,Pre,A,D,54.83,E,D,C,B,...,B,D,A,E,A,B,D,D,A,11.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,7,2.0,Pre,B,A,95.33,E,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
142,59,2.0,Pre,B,D,60.14,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
143,37,2.0,Pre,B,A,97.72,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [17]:
PostTestOnly = df[df.Test != 'Pre']
PostTestOnly

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,A,C,A,C,A,B,A,B,A,14.814815
5,82,1.0,Post,A,B+,84.94,B,D,D,D,...,E,B,C,C,A,NaN,D,D,C,33.333333
8,76,1.0,Post,A,A,95.57,E,NaN,D,D,...,C,C,D,A,C,NaN,D,D,A,29.629630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,40,2.0,Post,B,A,93.31,E,D,D,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.222222
141,7,2.0,Post,B,A,95.33,A,NaN,A,A,...,NaN,C,NaN,D,C,NaN,D,NaN,NaN,14.814815
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,18.518519
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,E,C,NaN,B,C,A,NaN,NaN,A,7.407407
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [59]:
AvgPreTestScore = PreTestOnly['TestScore'].mean().round(2)
PreTestScoresOverall = PreTestOnly['TestScore']

AvgPostTestScore = PostTestOnly['TestScore'].mean().round(2)
PostTestScoresOverall = PostTestOnly['TestScore']

print("Average Pre-test Score: " + str(AvgPreTestScore))
print("Pre-test Scores Overall: ")
sort_grades(PreTestScoresOverall)

print("\n")

print("Average Post-test Score: " + str(AvgPostTestScore))
print("Post-test Scores Overall: ")
sort_grades(PostTestScoresOverall)

Average Pre-test Score: 13.12
Pre-test Scores Overall:
   Number of students with a 90-100 grade: 0
   Number of students with a 80-89 grade: 0
   Number of students with a 70-79 grade: 0
   Number of students with a 60-69 grade: 0
   Number of students with a grade of 59 or lower: 81


Average Post-test Score: 20.48
Post-test Scores Overall:
   Number of students with a 90-100 grade: 0
   Number of students with a 80-89 grade: 0
   Number of students with a 70-79 grade: 1
   Number of students with a 60-69 grade: 0
   Number of students with a grade of 59 or lower: 69

In [19]:
# Conclusion:

# On average, there seems to be a slight increase in score between pre- and post-tests.

In [20]:
InstructorAOnly = df[df.Instructor != 'B']
InstructorAOnly

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,A,C,A,C,A,B,A,B,A,14.814815
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,A,B,A,NaN,C,NaN,NaN,NaN,NaN,25.925926
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,NaN,B,A,D,C,A,E,B,B,25.925926
5,82,1.0,Post,A,B+,84.94,B,D,D,D,...,E,B,C,C,A,NaN,D,D,C,33.333333
6,22,1.0,Pre,A,D,54.83,E,D,C,B,...,B,D,A,E,A,B,D,D,A,11.111111
7,76,1.0,Pre,A,A,95.57,A,NaN,D,NaN,...,NaN,NaN,E,NaN,C,NaN,NaN,NaN,NaN,14.814815
8,76,1.0,Post,A,A,95.57,E,NaN,D,D,...,C,C,D,A,C,NaN,D,D,A,29.629630
9,75,1.0,Pre,A,A,99.57,A,NaN,D,A,...,D,D,B,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
10,75,1.0,Post,A,A,99.57,E,E,D,B,...,C,D,D,C,C,NaN,B,NaN,A,44.444444
11,16,1.0,Post,A,A,97.80,D,C,A,D,...,C,C,D,B,C,B,D,B,A,29.629630
12,70,1.0,Pre,A,A,98.74,B,NaN,D,B,...,C,A,A,NaN,C,NaN,NaN,NaN,NaN,22.222222
13,70,1.0,Post,A,A,98.74,B,D,D,A,...,C,C,D,D,E,A,B,D,A,33.333333
14,5,1.0,Pre,A,C-,58.59,B,D,A,C,...,E,A,B,C,D,C,D,D,D,25.925926
15,84,1.0,Post,A,A,94.17,C,D,D,E,...,C,C,E,E,A,B,B,A,A,55.555556
16,84,1.0,Pre,A,A,94.17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
17,84,1.0,Pre,A,A,94.17,C,B,D,A,...,D,C,D,E,C,A,B,A,D,44.444444
18,80,1.0,Pre,A,D,48.11,NaN,D,A,C,...,D,NaN,D,NaN,C,NaN,A,NaN,NaN,22.222222
19,9,1.0,Pre,A,A,95.77,D,E,D,NaN,...,B,B,C,D,C,B,D,C,B,18.518519
20,9,1.0,Post,A,A,95.77,E,NaN,D,D,...,C,B,C,B,C,NaN,D,NaN,E,37.037037
21,54,1.0,Pre,A,B+,83.33,A,D,A,A,...,B,D,E,NaN,C,A,D,A,D,18.518519
22,54,1.0,Post,A,B+,83.33,E,B,A,B,...,E,C,D,NaN,C,A,C,C,A,14.814815
23,51,1.0,Pre,A,W,36.21,B,D,A,B,...,A,A,C,B,B,C,A,D,D,11.111111
24,68,1.0,Pre,A,B-,74.40,D,B,D,B,...,D,B,C,D,C,B,C,D,B,22.222222
25,68,1.0,Post,A,B-,74.40,E,E,D,E,...,D,A,D,A,C,B,C,D,D,25.925926
26,71,1.0,Pre,A,A,93.61,C,NaN,NaN,NaN,...,D,B,C,D,B,D,D,NaN,B,22.222222
27,71,1.0,Post,A,A,93.61,E,D,D,C,...,E,D,A,B,C,B,C,D,B,25.925926
28,43,1.0,Pre,A,D,57.50,A,D,C,D,...,C,D,D,B,C,B,C,A,C,29.629630
29,43,1.0,Post,A,D,57.50,A,E,E,D,...,C,B,B,D,C,D,B,B,C,37.037037
30,56,1.0,Pre,A,W,23.14,B,C,A,D,...,E,A,E,C,B,A,D,B,A,11.111111
31,10,1.0,Pre,A,C,69.36,A,NaN,NaN,B,...,NaN,A,E,C,NaN,B,E,C,B,7.407407
32,10,1.0,Post,A,C,69.36,E,D,D,D,...,NaN,E,D,A,C,A,D,D,B,29.629630
33,65,1.0,Pre,A,C,71.53,A,A,A,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
34,65,1.0,Post,A,C,71.53,E,C,A,A,...,E,B,A,B,A,A,E,A,A,18.518519
35,83,1.0,Pre,A,A,96.81,D,E,D,D,...,E,B,B,C,C,B,B,B,D,33.333333
36,83,1.0,Post,A,A,96.81,E,D,D,C,...,E,C,C,C,B,A,B,A,A,33.333333
37,20,1.0,Pre,A,W,0.00,E,B,D,C,...,C,A,D,C,D,C,D,C,C,25.925926
38,46,1.0,Post,A,B-,75.55,C,C,D,E,...,D,B,D,B,B,C,NaN,NaN,NaN,33.333333
39,46,1.0,Pre,A,B-,73.01,C,A,D,C,...,E,B,E,A,C,D,C,A,B,22.222222
40,53,1.0,Pre,A,A,94.31,A,NaN,NaN,NaN,...,NaN,B,NaN,NaN,C,NaN,B,NaN,NaN,18.518519
41,53,1.0,Post,A,A,94.31,E,NaN,E,E,...,A,B,E,C,C,A,B,NaN,D,48.148148
42,78,1.0,Pre,A,C,66.93,D,E,C,B,...,E,C,C,D,B,D,C,C,C,11.111111
43,78,1.0,Post,A,C,66.93,E,D,E,D,...,C,E,B,C,B,C,C,B,A,22.222222
44,48,1.0,Pre,A,C+,73.95,B,D,B,B,...,A,D,C,B,A,D,D,B,D,14.814815
45,48,1.0,Post,A,C+,73.95,C,D,B,A,...,C,C,B,B,E,C,A,D,B,14.814815
46,72,1.0,Post,A,B-,73.66,E,NaN,D,E,...,C,D,D,C,C,NaN,B,NaN,A,51.851852
47,26,1.0,Pre,A,W,0.00,A,B,D,E,...,A,D,C,D,A,C,B,E,A,25.925926
48,2,1.0,Pre,A,F,8.45,A,D,B,C,...,E,B,B,C,D,NaN,E,B,C,22.222222
49,23,1.0,Post,A,A,87.19,B,E,D,E,...,C,B,D,C,C,D,B,A,D,77.777778
50,4,1.0,Pre,A,W,0.00,D,A,E,NaN,...,C,D,D,B,B,D,NaN,D,NaN,25.925926
51,25,1.0,Post,A,B+,84.12,B,B,A,A,...,A,D,A,A,B,A,B,C,C,11.111111
52,74,1.0,Pre,A,B-,74.82,A,E,B,E,...,D,A,D,C,E,C,B,A,D,37.037037
53,74,1.0,Post,A,B-,74.82,A,C,D,B,...,E,D,B,B,B,D,D,C,D,22.222222
54,79,1.0,Pre,A,D,30.07,C,C,E,NaN,...,E,B,A,C,C,NaN,C,E,C,25.925926
55,67,1.0,Pre,A,C-,43.64,B,D,A,C,...,E,B,B,B,E,A,D,A,B,14.814815
56,67,1.0,Post,A,C-,43.64,B,D,A,A,...,D,B,E,C,B,E,D,D,D,25.925926

In [21]:
InstructorBOnly = df[df.Instructor != 'A']
InstructorBOnly

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
57,33,1.0,Pre,B,A,93.60,B,NaN,A,NaN,...,NaN,NaN,B,B,NaN,NaN,NaN,NaN,NaN,22.222222
58,33,1.0,Post,B,A,93.60,D,NaN,B,B,...,C,B,B,B,C,C,D,A,B,25.925926
59,60,1.0,Pre,B,C-,70.49,E,C,C,E,...,C,B,A,NaN,B,NaN,NaN,NaN,NaN,18.518519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,18.518519
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,E,C,NaN,B,C,A,NaN,NaN,A,7.407407
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [22]:
AvgFinalAGrade = InstructorAOnly['PercentGrade'].mean().round(2)
AvgFinalBGrade = InstructorBOnly['PercentGrade'].mean().round(2)

print("Average Final Grade For Instructor A's Class: " + str(AvgFinalAGrade))
print("Average Final Grade For Instructor B's Class: " + str(AvgFinalBGrade))

Average Final Grade For Instructor A's Class: 70.0
Average Final Grade For Instructor B's Class: 87.27

In [23]:
# On average, the final grades for instructor A's class as a whole seem to be lower than the final grades of
# instructor B's class as a whole.

In [24]:
Term1Only = df[df.Term != 2.0]
Term1Only

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2,22,1.0,Post,A,D,54.83,D,C,B,C,...,A,C,A,C,A,B,A,B,A,14.814815
3,50,1.0,Pre,A,F,12.41,A,NaN,A,NaN,...,A,B,A,NaN,C,NaN,NaN,NaN,NaN,25.925926
4,82,1.0,Pre,A,B+,84.94,C,C,A,C,...,NaN,B,A,D,C,A,E,B,B,25.925926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8,1.0,Post,B,B-,80.19,D,A,A,C,...,NaN,C,NaN,E,C,NaN,C,C,C,18.518519
97,63,1.0,Post,B,A,99.34,E,A,D,D,...,D,B,C,E,B,D,A,D,B,33.333333
98,63,1.0,Pre,B,A,99.34,NaN,D,E,NaN,...,E,C,E,NaN,D,NaN,B,C,D,18.518519
99,14,1.0,Pre,B,C,76.05,D,B,B,D,...,D,C,B,D,C,B,B,D,D,29.629630
100,86,1.0,Post,B,C,76.05,NaN,E,A,B,...,E,B,D,B,A,C,D,E,B,11.111111

In [25]:
Term2Only = df[df.Term != 1.0]
Term2Only

,Participant Code,Term,Test,Instructor,LetterGrade,PercentGrade,Q1,Q2,Q3,Q4,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,TestScore
0,KEY,NaN,NaN,NaN,NaN,NaN,E,D,D,E,...,C,B,D,C,C,D,B,A,D,0.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
101,6,2.0,Pre,B,A,99.38,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
102,31,2.0,Pre,B,A,94.57,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
103,31,2.0,Post,B,A,94.57,NaN,C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
104,38,2.0,Pre,B,A,99.67,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
105,38,2.0,Post,B,A,99.67,E,E,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
106,22,2.0,Pre,B,D+,66.69,A,B,B,C,...,D,B,A,B,B,C,B,D,A,22.222222
107,22,2.0,Post,B,D+,66.69,A,C,B,C,...,C,D,A,C,A,C,B,D,A,18.518519
108,62,2.0,Post,B,B,82.66,C,NaN,B,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
109,57,2.0,Pre,B,A,106.00,A,A,D,A,...,NaN,C,NaN,NaN,C,NaN,D,NaN,A,18.518519
110,57,2.0,Post,B,A,106.00,E,NaN,D,E,...,C,A,NaN,NaN,C,NaN,B,NaN,D,33.333333
111,15,2.0,Pre,B,C,74.94,C,NaN,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
112,15,2.0,Post,B,C,74.94,NaN,NaN,A,NaN,...,NaN,NaN,NaN,NaN,C,NaN,D,NaN,NaN,3.703704
113,45,2.0,Pre,B,A,95.51,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
114,45,2.0,Post,B,A,95.51,E,D,A,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.814815
115,27,2.0,Pre,B,A,99.75,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
116,27,2.0,Post,B,A,99.75,E,D,D,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.814815
117,41,2.0,Pre,B,C,73.58,C,NaN,D,B,...,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.814815
118,41,2.0,Post,B,C,73.58,NaN,NaN,A,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.814815
119,52,2.0,Pre,B,A-,90.78,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
120,52,2.0,Post,B,A-,90.78,E,NaN,NaN,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
121,66,2.0,Pre,B,C,73.94,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
122,66,2.0,Post,B,C,73.94,A,D,D,NaN,...,B,C,E,D,B,E,C,A,E,14.814815
123,18,2.0,Pre,B,A,101.81,NaN,B,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
124,18,2.0,Post,B,A,101.81,B,D,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.814815
125,32,2.0,Pre,B,C+,76.92,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
126,32,2.0,Post,B,C+,76.92,D,C,A,NaN,...,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.111111
127,13,2.0,Pre,B,A,98.63,B,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
128,13,2.0,Post,B,A,98.63,D,C,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
129,29,2.0,Pre,B,A,99.83,A,D,A,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
130,36,2.0,Pre,B,A,97.53,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
131,36,2.0,Post,B,A,97.53,A,E,A,NaN,...,C,A,D,C,B,E,B,E,A,25.925926
132,12,2.0,Pre,B,A,99.26,E,D,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.111111
133,12,2.0,Post,B,A,99.26,C,D,D,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.814815
134,1,2.0,Pre,B,A,97.72,B,C,A,C,...,B,E,B,B,B,C,A,A,B,14.814815
135,1,2.0,Post,B,A,97.72,A,B,D,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
136,11,2.0,Pre,B,A,98.52,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
137,11,2.0,Post,B,A,98.52,NaN,D,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
138,40,2.0,Pre,B,A,93.31,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
139,40,2.0,Post,B,A,93.31,E,D,D,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.222222
140,7,2.0,Pre,B,A,95.33,E,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
141,7,2.0,Post,B,A,95.33,A,NaN,A,A,...,NaN,C,NaN,D,C,NaN,D,NaN,NaN,14.814815
142,59,2.0,Pre,B,D,60.14,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
143,37,2.0,Pre,B,A,97.72,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.703704
144,37,2.0,Post,B,A,97.72,A,D,D,D,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,NaN,18.518519
145,42,2.0,Post,B,B+,87.81,D,NaN,A,NaN,...,E,C,NaN,B,C,A,NaN,NaN,A,7.407407
146,42,2.0,Pre,B,B+,87.81,C,C,NaN,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.407407
147,79,2.0,Pre,B,B+,86.68,D,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
148,79,2.0,Post,B,B+,86.68,B,E,B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [26]:
AvgTerm1Grade = Term1Only['PercentGrade'].mean().round(2)
AvgTerm2Grade = Term2Only['PercentGrade'].mean().round(2)

print("Average Final Grade For Term 1: " + str(AvgTerm1Grade))
print("Average Final Grade For Term 2: " + str(AvgTerm2Grade))

Average Final Grade For Term 1: 75.99
Average Final Grade For Term 2: 90.74

In [27]:
# On average, for the classes as a whole, students in Term 2 had a better final grade than the students in Term 1